import {
  OFFICIAL_DISTRICTS,
  formatDistrictName,
} from '@/lib/location/districts';

export {
  OFFICIAL_DISTRICTS,
  formatDistrictName,
} from '@/lib/location/districts';

// lib/utils/district-normalization.ts

export type Parity = 'ODD' | 'EVEN' | 'BOTH';

export interface SplitRule {
  district: string;
  parity: Parity;
  min: number;
  max: number;
}

export const SPLIT_STREETS_CONFIG: Record<string, SplitRule[]> = {
  'armii krajowej': [
    { district: 'ŚRÓDMIEŚCIE', parity: 'ODD', min: 1, max: 5 },
    { district: 'ŚRÓDMIEŚCIE', parity: 'BOTH', min: 2, max: 2 },
    { district: 'TYSIĄCLECIE', parity: 'ODD', min: 7, max: 25 },
    { district: 'TYSIĄCLECIE', parity: 'ODD', min: 31, max: 99999 },
    { district: 'TYSIĄCLECIE', parity: 'EVEN', min: 4, max: 99999 },
  ],
  'bohaterów katynia': [
    { district: 'BŁESZNO', parity: 'ODD', min: 39, max: 99999 },
    { district: 'BŁESZNO', parity: 'EVEN', min: 56, max: 99999 },
    { district: 'WRZOSOWIAK', parity: 'ODD', min: 1, max: 37 },
    { district: 'WRZOSOWIAK', parity: 'EVEN', min: 2, max: 52 },
  ],
  bór: [
    { district: 'BŁESZNO', parity: 'ODD', min: 107, max: 99999 },
    { district: 'BŁESZNO', parity: 'EVEN', min: 106, max: 99999 },
    { district: 'OSTATNI GROSZ', parity: 'ODD', min: 1, max: 105 },
    { district: 'OSTATNI GROSZ', parity: 'EVEN', min: 2, max: 104 },
  ],
  'gen. jana henryka dąbrowskiego': [
    { district: 'ŚRÓDMIEŚCIE', parity: 'ODD', min: 1, max: 37 },
    { district: 'ŚRÓDMIEŚCIE', parity: 'EVEN', min: 2, max: 30 },
    { district: 'TYSIĄCLECIE', parity: 'ODD', min: 39, max: 99999 },
    { district: 'TYSIĄCLECIE', parity: 'EVEN', min: 32, max: 99999 },
  ],
  'gen. kazimierza pułaskiego': [
    { district: 'PODJASNOGÓRSKA', parity: 'EVEN', min: 2, max: 99999 },
    { district: 'ŚRÓDMIEŚCIE', parity: 'ODD', min: 1, max: 25 },
    { district: 'TRZECH WIESZCZÓW', parity: 'ODD', min: 27, max: 99999 },
  ],
  'gen. romualda traugutta': [
    { district: 'KIEDRZYN', parity: 'ODD', min: 85, max: 99999 },
    { district: 'KIEDRZYN', parity: 'EVEN', min: 74, max: 99999 },
    { district: 'TYSIĄCLECIE', parity: 'ODD', min: 1, max: 83 },
    { district: 'TYSIĄCLECIE', parity: 'EVEN', min: 2, max: 72 },
  ],
  'gen. władysława sikorskiego': [
    { district: 'CZĘSTOCHÓWKA-PARKITKA', parity: 'ODD', min: 11, max: 99999 },
    { district: 'CZĘSTOCHÓWKA-PARKITKA', parity: 'EVEN', min: 16, max: 99999 },
    { district: 'TYSIĄCLECIE', parity: 'ODD', min: 1, max: 9 },
    { district: 'TYSIĄCLECIE', parity: 'EVEN', min: 2, max: 14 },
  ],
  jagiellońska: [
    { district: 'OSTATNI GROSZ', parity: 'EVEN', min: 30, max: 50 },
    { district: 'STRADOM', parity: 'ODD', min: 111, max: 99999 },
    { district: 'STRADOM', parity: 'EVEN', min: 52, max: 99999 },
    { district: 'WRZOSOWIAK', parity: 'ODD', min: 1, max: 109 },
    { district: 'WRZOSOWIAK', parity: 'EVEN', min: 2, max: 28 },
  ],
  'jana kilińskiego': [
    { district: 'ŚRÓDMIEŚCIE', parity: 'ODD', min: 1, max: 29 },
    { district: 'ŚRÓDMIEŚCIE', parity: 'EVEN', min: 2, max: 46 },
    { district: 'TYSIĄCLECIE', parity: 'ODD', min: 31, max: 99999 },
    { district: 'TYSIĄCLECIE', parity: 'EVEN', min: 48, max: 99999 },
  ],
  'jana pawła ii': [
    { district: 'CZĘSTOCHÓWKA-PARKITKA', parity: 'ODD', min: 111, max: 99999 },
    { district: 'CZĘSTOCHÓWKA-PARKITKA', parity: 'EVEN', min: 118, max: 99999 },
    { district: 'STARE MIASTO', parity: 'ODD', min: 1, max: 41 },
    { district: 'STARE MIASTO', parity: 'EVEN', min: 2, max: 24 },
    { district: 'ŚRÓDMIEŚCIE', parity: 'ODD', min: 43, max: 109 },
    { district: 'TYSIĄCLECIE', parity: 'EVEN', min: 26, max: 116 },
  ],
  'kardynała stefana wyszyńskiego': [
    { district: 'CZĘSTOCHÓWKA-PARKITKA', parity: 'ODD', min: 1, max: 65 },
    { district: 'CZĘSTOCHÓWKA-PARKITKA', parity: 'EVEN', min: 2, max: 60 },
    { district: 'LISINIEC', parity: 'ODD', min: 67, max: 99999 },
    { district: 'LISINIEC', parity: 'EVEN', min: 62, max: 99999 },
  ],
  kiedrzyńska: [
    { district: 'STARE MIASTO', parity: 'ODD', min: 1, max: 45 },
    { district: 'STARE MIASTO', parity: 'EVEN', min: 2, max: 46 },
    { district: 'TYSIĄCLECIE', parity: 'ODD', min: 47, max: 99999 },
    { district: 'TYSIĄCLECIE', parity: 'EVEN', min: 48, max: 99999 },
  ],
  'kornela makuszyńskiego': [
    { district: 'PÓŁNOC', parity: 'ODD', min: 39, max: 99999 },
    { district: 'PÓŁNOC', parity: 'EVEN', min: 52, max: 99999 },
    { district: 'WYCZERPY-ANIOŁÓW', parity: 'ODD', min: 1, max: 37 },
    { district: 'WYCZERPY-ANIOŁÓW', parity: 'EVEN', min: 2, max: 50 },
  ],
  lwowska: [
    { district: 'GNASZYN-KAWODRZA', parity: 'ODD', min: 179, max: 99999 },
    { district: 'GNASZYN-KAWODRZA', parity: 'EVEN', min: 158, max: 99999 },
    { district: 'LISINIEC', parity: 'ODD', min: 1, max: 177 },
    { district: 'LISINIEC', parity: 'EVEN', min: 2, max: 156 },
  ],
  mirowska: [
    { district: 'MIRÓW', parity: 'ODD', min: 49, max: 99999 },
    { district: 'MIRÓW', parity: 'EVEN', min: 52, max: 99999 },
    { district: 'STARE MIASTO', parity: 'ODD', min: 1, max: 13 },
    { district: 'STARE MIASTO', parity: 'EVEN', min: 2, max: 20 },
    { district: 'ZAWODZIE-DĄBIE', parity: 'ODD', min: 17, max: 47 },
    { district: 'ZAWODZIE-DĄBIE', parity: 'EVEN', min: 22, max: 50 },
  ],
  'najświętszej maryi panny': [
    { district: 'STARE MIASTO', parity: 'ODD', min: 1, max: 15 },
    { district: 'STARE MIASTO', parity: 'EVEN', min: 2, max: 14 },
    { district: 'ŚRÓDMIEŚCIE', parity: 'ODD', min: 17, max: 99999 },
    { district: 'ŚRÓDMIEŚCIE', parity: 'EVEN', min: 16, max: 99999 },
  ],
  niepodległości: [
    { district: 'OSTATNI GROSZ', parity: 'ODD', min: 1, max: 99999 },
    { district: 'OSTATNI GROSZ', parity: 'EVEN', min: 2, max: 30 },
    { district: 'WRZOSOWIAK', parity: 'EVEN', min: 32, max: 50 },
  ],
  pokoju: [
    { district: 'RAKÓW', parity: 'ODD', min: 1, max: 17 },
    { district: 'RAKÓW', parity: 'EVEN', min: 2, max: 22 },
    { district: 'ZAWODZIE-DĄBIE', parity: 'ODD', min: 19, max: 99999 },
    { district: 'ZAWODZIE-DĄBIE', parity: 'EVEN', min: 24, max: 99999 },
  ],
  przestrzenna: [
    { district: 'GNASZYN-KAWODRZA', parity: 'ODD', min: 1, max: 31 },
    { district: 'GNASZYN-KAWODRZA', parity: 'EVEN', min: 2, max: 16 },
    { district: 'STRADOM', parity: 'ODD', min: 33, max: 99999 },
    { district: 'STRADOM', parity: 'EVEN', min: 18, max: 99999 },
  ],
  sokola: [
    { district: 'GNASZYN-KAWODRZA', parity: 'ODD', min: 1, max: 23 },
    { district: 'GNASZYN-KAWODRZA', parity: 'EVEN', min: 2, max: 34 },
    { district: 'STRADOM', parity: 'ODD', min: 25, max: 99999 },
    { district: 'STRADOM', parity: 'EVEN', min: 36, max: 99999 },
  ],
  'stefana kisielewskiego': [
    { district: 'KIEDRZYN', parity: 'ODD', min: 43, max: 99999 },
    { district: 'KIEDRZYN', parity: 'EVEN', min: 28, max: 99999 },
    { district: 'TYSIĄCLECIE', parity: 'ODD', min: 1, max: 41 },
    { district: 'TYSIĄCLECIE', parity: 'EVEN', min: 2, max: 16 },
  ],
  tatrzańska: [
    { district: 'GNASZYN-KAWODRZA', parity: 'ODD', min: 1, max: 3 },
    { district: 'GNASZYN-KAWODRZA', parity: 'EVEN', min: 2, max: 4 },
    { district: 'LISINIEC', parity: 'ODD', min: 5, max: 99999 },
    { district: 'LISINIEC', parity: 'EVEN', min: 6, max: 99999 },
  ],
  warszawska: [
    { district: 'STARE MIASTO', parity: 'ODD', min: 1, max: 129 },
    { district: 'STARE MIASTO', parity: 'EVEN', min: 2, max: 152 },
    { district: 'WYCZERPY-ANIOŁÓW', parity: 'ODD', min: 131, max: 99999 },
    { district: 'WYCZERPY-ANIOŁÓW', parity: 'EVEN', min: 154, max: 99999 },
  ],
  'wały dwernickiego': [
    { district: 'ŚRÓDMIEŚCIE', parity: 'ODD', min: 1, max: 49 },
    { district: 'TYSIĄCLECIE', parity: 'ODD', min: 51, max: 99999 },
  ],
  wichrowa: [
    { district: 'GNASZYN-KAWODRZA', parity: 'ODD', min: 1, max: 7 },
    { district: 'GNASZYN-KAWODRZA', parity: 'EVEN', min: 2, max: 6 },
    { district: 'LISINIEC', parity: 'ODD', min: 9, max: 99999 },
    { district: 'LISINIEC', parity: 'EVEN', min: 8, max: 99999 },
  ],
  'wojska polskiego': [
    { district: 'BŁESZNO', parity: 'ODD', min: 1, max: 71 },
    { district: 'BŁESZNO', parity: 'EVEN', min: 2, max: 108 },
    { district: 'OSTATNI GROSZ', parity: 'ODD', min: 89, max: 137 },
    { district: 'OSTATNI GROSZ', parity: 'EVEN', min: 134, max: 150 },
    { district: 'RAKÓW', parity: 'EVEN', min: 110, max: 132 },
    { district: 'STARE MIASTO', parity: 'ODD', min: 159, max: 213 },
    { district: 'WRZOSOWIAK', parity: 'ODD', min: 73, max: 87 },
    { district: 'WYCZERPY-ANIOŁÓW', parity: 'ODD', min: 271, max: 99999 },
    { district: 'WYCZERPY-ANIOŁÓW', parity: 'EVEN', min: 252, max: 99999 },
    { district: 'ZAWODZIE-DĄBIE', parity: 'ODD', min: 235, max: 261 },
    { district: 'ZAWODZIE-DĄBIE', parity: 'EVEN', min: 152, max: 250 },
  ],
  wolności: [
    { district: 'ŚRÓDMIEŚCIE', parity: 'ODD', min: 1, max: 49 },
    { district: 'ŚRÓDMIEŚCIE', parity: 'EVEN', min: 2, max: 42 },
    { district: 'TRZECH WIESZCZÓW', parity: 'ODD', min: 51, max: 99999 },
    { district: 'TRZECH WIESZCZÓW', parity: 'EVEN', min: 44, max: 99999 },
  ],
  zaciszańska: [
    { district: 'PODJASNOGÓRSKA', parity: 'ODD', min: 1, max: 23 },
    { district: 'PODJASNOGÓRSKA', parity: 'EVEN', min: 2, max: 16 },
    { district: 'STRADOM', parity: 'ODD', min: 25, max: 99999 },
    { district: 'STRADOM', parity: 'EVEN', min: 18, max: 99999 },
  ],
  łomżyńska: [
    { district: 'GNASZYN-KAWODRZA', parity: 'ODD', min: 155, max: 99999 },
    { district: 'LISINIEC', parity: 'ODD', min: 1, max: 153 },
    { district: 'LISINIEC', parity: 'EVEN', min: 2, max: 99999 },
  ],
  'św. jadwigi': [
    { district: 'CZĘSTOCHÓWKA-PARKITKA', parity: 'ODD', min: 1, max: 135 },
    { district: 'CZĘSTOCHÓWKA-PARKITKA', parity: 'EVEN', min: 2, max: 90 },
    { district: 'PODJASNOGÓRSKA', parity: 'ODD', min: 137, max: 99999 },
    { district: 'PODJASNOGÓRSKA', parity: 'EVEN', min: 92, max: 99999 },
  ],
  'św. rocha': [
    { district: 'CZĘSTOCHÓWKA-PARKITKA', parity: 'ODD', min: 1, max: 217 },
    { district: 'CZĘSTOCHÓWKA-PARKITKA', parity: 'EVEN', min: 2, max: 180 },
    { district: 'GRABÓWKA', parity: 'ODD', min: 219, max: 99999 },
    { district: 'GRABÓWKA', parity: 'EVEN', min: 182, max: 99999 },
  ],
  żarecka: [
    { district: 'BŁESZNO', parity: 'ODD', min: 147, max: 99999 },
    { district: 'BŁESZNO', parity: 'EVEN', min: 172, max: 99999 },
    { district: 'RAKÓW', parity: 'ODD', min: 1, max: 145 },
    { district: 'RAKÓW', parity: 'EVEN', min: 2, max: 170 },
  ],
};

export const STREET_TO_DISTRICT_MAP: Record<string, string> = {
  '1 maja': 'TRZECH WIESZCZÓW',
  '10 zakładników': 'GNASZYN-KAWODRZA',
  '11 listopada': 'WRZOSOWIAK',
  '3 maja': 'CZĘSTOCHÓWKA-PARKITKA',
  '7 kamienic': 'PODJASNOGÓRSKA',
  'adama asnyka': 'RAKÓW',
  'adama bienia': 'WRZOSOWIAK',
  'adama mickiewicza': 'TRZECH WIESZCZÓW',
  'adama naruszewicza': 'WYCZERPY-ANIOŁÓW',
  'adama próchnika': 'RAKÓW',
  admiralska: 'STRADOM',
  'adriana głębockiego': 'PÓŁNOC',
  akacjowa: 'GNASZYN-KAWODRZA',
  akademicka: 'TYSIĄCLECIE',
  'alberta einsteina': 'ZAWODZIE-DĄBIE',
  'aleksandra czekanowskiego': 'PÓŁNOC',
  'aleksandra fredry': 'RAKÓW',
  'aleksandra gierymskiego': 'STRADOM',
  'aleksandra kamińskiego': 'WRZOSOWIAK',
  'aleksandra szymona grabary': 'PÓŁNOC',
  'aleksandra zelwerowicza': 'WYCZERPY-ANIOŁÓW',
  aluminiowa: 'ZAWODZIE-DĄBIE',
  ambulatoryjna: 'TRZECH WIESZCZÓW',
  amonitowa: 'GNASZYN-KAWODRZA',
  'andrzeja struga': 'RAKÓW',
  'andrzeja towiańskiego': 'RAKÓW',
  aniołowska: 'WYCZERPY-ANIOŁÓW',
  'anny walentynowicz': 'KIEDRZYN',
  'antoniego fertnera': 'WYCZERPY-ANIOŁÓW',
  'antoniego i władysława krzemińskich': 'KIEDRZYN',
  'antoniego słonimskiego': 'TYSIĄCLECIE',
  anyżkowa: 'DŹBÓW',
  arrasowa: 'GNASZYN-KAWODRZA',
  'artura grottgera': 'STRADOM',
  'artura oppmana or-ota': 'WYCZERPY-ANIOŁÓW',
  artyleryjska: 'STRADOM',
  astronautów: 'STRADOM',
  augustowska: 'CZĘSTOCHÓWKA-PARKITKA',
  azaliowa: 'KIEDRZYN',
  babia: 'ZAWODZIE-DĄBIE',
  bagienna: 'GNASZYN-KAWODRZA',
  bajeczna: 'GNASZYN-KAWODRZA',
  bakaliowa: 'BŁESZNO',
  balladyny: 'GNASZYN-KAWODRZA',
  balonowa: 'STRADOM',
  bartnicza: 'ZAWODZIE-DĄBIE',
  'bartosza głowackiego': 'ZAWODZIE-DĄBIE',
  barwna: 'BŁESZNO',
  'batalionów chłopskich': 'WYCZERPY-ANIOŁÓW',
  bałtycka: 'BŁESZNO',
  baśniowa: 'GNASZYN-KAWODRZA',
  bażantowa: 'STRADOM',
  'benedykta dybowskiego': 'PÓŁNOC',
  'berka joselewicza': 'STARE MIASTO',
  'bernarda ludwika hantkego': 'ZAWODZIE-DĄBIE',
  beskidzka: 'GRABÓWKA',
  bełchatowska: 'LISINIEC',
  bialska: 'CZĘSTOCHÓWKA-PARKITKA',
  biała: 'GRABÓWKA',
  białostocka: 'LISINIEC',
  białowieska: 'LISINIEC',
  bieszczadzka: 'LISINIEC',
  'biskupa teodora kubiny': 'CZĘSTOCHÓWKA-PARKITKA',
  biurowa: 'DŹBÓW',
  biwakowa: 'BŁESZNO',
  blachowieńska: 'LISINIEC',
  'blaise pascala': 'WYCZERPY-ANIOŁÓW',
  bliska: 'ZAWODZIE-DĄBIE',
  bocheńska: 'LISINIEC',
  bociania: 'ZAWODZIE-DĄBIE',
  boczna: 'ZAWODZIE-DĄBIE',
  bohaterska: 'GNASZYN-KAWODRZA',
  'bohaterów monte cassino': 'TRZECH WIESZCZÓW',
  bohuna: 'STRADOM',
  'bolesława chrobrego': 'STRADOM',
  'bolesława leśmiana': 'RAKÓW',
  'bolesława limanowskiego': 'RAKÓW',
  'bolesława micińskiego': 'WYCZERPY-ANIOŁÓW',
  'bolesława prusa': 'RAKÓW',
  'bony sforzy': 'PODJASNOGÓRSKA',
  borówkowa: 'GNASZYN-KAWODRZA',
  botaniczna: 'WRZOSOWIAK',
  bratkowa: 'KIEDRZYN',
  bratnia: 'ZAWODZIE-DĄBIE',
  broni: 'STRADOM',
  'bronisława czecha': 'PÓŁNOC',
  'bronisława hubermana': 'WYCZERPY-ANIOŁÓW',
  'bronisława idzikowskiego': 'ZAWODZIE-DĄBIE',
  'bruno schulza': 'RAKÓW',
  brzegowa: 'ZAWODZIE-DĄBIE',
  brzezińska: 'BŁESZNO',
  brzeźnicka: 'TYSIĄCLECIE',
  brzozowa: 'WRZOSOWIAK',
  brzyszowska: 'MIRÓW',
  budowlanych: 'ZAWODZIE-DĄBIE',
  bugaj: 'BŁESZNO',
  bugajska: 'BŁESZNO',
  bukowa: 'WRZOSOWIAK',
  bursztynowa: 'MIRÓW',
  busolowa: 'DŹBÓW',
  bydgoska: 'LISINIEC',
  bystra: 'ZAWODZIE-DĄBIE',
  bytomska: 'LISINIEC',
  będzińska: 'LISINIEC',
  'bł. jolanty': 'PODJASNOGÓRSKA',
  'bł. salomei': 'PODJASNOGÓRSKA',
  bławatkowa: 'KIEDRZYN',
  błotna: 'OSTATNI GROSZ',
  cedrowa: 'WRZOSOWIAK',
  cegielniana: 'GNASZYN-KAWODRZA',
  ceglana: 'ZAWODZIE-DĄBIE',
  ceramiczna: 'ZAWODZIE-DĄBIE',
  chabrowa: 'LISINIEC',
  chmielna: 'DŹBÓW',
  chochołowska: 'LISINIEC',
  chorzowska: 'LISINIEC',
  chęcińska: 'LISINIEC',
  chłodna: 'ZAWODZIE-DĄBIE',
  chłopska: 'DŹBÓW',
  ciasna: 'TRZECH WIESZCZÓW',
  cicha: 'STARE MIASTO',
  ciechanowska: 'CZĘSTOCHÓWKA-PARKITKA',
  cienista: 'DŹBÓW',
  ciepła: 'ZAWODZIE-DĄBIE',
  cieszyńska: 'LISINIEC',
  cisowa: 'WRZOSOWIAK',
  cmentarna: 'WYCZERPY-ANIOŁÓW',
  'cypriana godebskiego': 'TYSIĄCLECIE',
  'cypriana kamila norwida': 'WYCZERPY-ANIOŁÓW',
  cyprysowa: 'WYCZERPY-ANIOŁÓW',
  cyrklowa: 'LISINIEC',
  czeremchowa: 'DŹBÓW',
  czereśniowa: 'STRADOM',
  'czesława miłosza': 'KIEDRZYN',
  czołgistów: 'STRADOM',
  czwartaków: 'TYSIĄCLECIE',
  czysta: 'ZAWODZIE-DĄBIE',
  częstocha: 'TYSIĄCLECIE',
  'daniela chodowieckiego': 'STRADOM',
  danusi: 'STRADOM',
  dawna: 'GRABÓWKA',
  dedala: 'GRABÓWKA',
  dekabrystów: 'TYSIĄCLECIE',
  deszczowa: 'GNASZYN-KAWODRZA',
  diamentowa: 'GNASZYN-KAWODRZA',
  dobra: 'ZAWODZIE-DĄBIE',
  dobrzyńska: 'LISINIEC',
  'doc. dra alfreda leonarda czarnoty': 'TYSIĄCLECIE',
  dojazdowa: 'BŁESZNO',
  dolna: 'OSTATNI GROSZ',
  'dominika zbierskiego': 'TYSIĄCLECIE',
  dowódców: 'STRADOM',
  'dra ludwika zamenhofa': 'RAKÓW',
  'dra tytusa chałubińskiego': 'ZAWODZIE-DĄBIE',
  'dra witolda orłowskiego': 'GNASZYN-KAWODRZA',
  drogowców: 'WYCZERPY-ANIOŁÓW',
  drozdowa: 'ZAWODZIE-DĄBIE',
  druciana: 'GNASZYN-KAWODRZA',
  drzewna: 'GNASZYN-KAWODRZA',
  dusznicka: 'LISINIEC',
  'dymitra mendelejewa': 'ZAWODZIE-DĄBIE',
  działowa: 'STRADOM',
  dzielna: 'ZAWODZIE-DĄBIE',
  dzika: 'ZAWODZIE-DĄBIE',
  dąbrówki: 'STRADOM',
  dębowa: 'ZAWODZIE-DĄBIE',
  długa: 'BŁESZNO',
  dźbowska: 'STRADOM',
  'edwarda mąkoszy': 'ŚRÓDMIEŚCIE',
  ekonomiczna: 'DŹBÓW',
  elbląska: 'LISINIEC',
  elektryków: 'GNASZYN-KAWODRZA',
  'elizy orzeszkowej': 'RAKÓW',
  'emila zegadłowicza': 'WYCZERPY-ANIOŁÓW',
  'emilii plater': 'WYCZERPY-ANIOŁÓW',
  energetyków: 'GNASZYN-KAWODRZA',
  'eugeniusza kwiatkowskiego': 'TYSIĄCLECIE',
  'eugeniusza romera': 'TYSIĄCLECIE',
  'eugeniusza seifrieda': 'WYCZERPY-ANIOŁÓW',
  'eugeniusza żychlińskiego': 'BŁESZNO',
  ewy: 'CZĘSTOCHÓWKA-PARKITKA',
  falista: 'MIRÓW',
  'feliksa nowowiejskiego': 'ŚRÓDMIEŚCIE',
  'feliksa perla': 'RAKÓW',
  festynowa: 'GNASZYN-KAWODRZA',
  filomatów: 'TRZECH WIESZCZÓW',
  filtrowa: 'MIRÓW',
  'fiodora dostojewskiego': 'WYCZERPY-ANIOŁÓW',
  fiołkowa: 'KIEDRZYN',
  flisacka: 'GRABÓWKA',
  forteczna: 'STRADOM',
  'franciszka dionizego wilkoszewskiego': 'PÓŁNOC',
  'franciszka karpińskiego': 'RAKÓW',
  'franciszka żmurki': 'STRADOM',
  'franciszka żwirki i stanisława wigury': 'ŚRÓDMIEŚCIE',
  fromborska: 'LISINIEC',
  'fryderyka chopina': 'STRADOM',
  'gabrieli zapolskiej': 'TYSIĄCLECIE',
  gajowa: 'WRZOSOWIAK',
  'galla anonima': 'STARE MIASTO',
  garbarska: 'ZAWODZIE-DĄBIE',
  garncarska: 'STARE MIASTO',
  garwolińska: 'LISINIEC',
  gazowa: 'OSTATNI GROSZ',
  gdańska: 'LISINIEC',
  gdyńska: 'LISINIEC',
  'gen. antoniego madalińskiego': 'WYCZERPY-ANIOŁÓW',
  'gen. augusta fieldorfa-nila': 'PÓŁNOC',
  'gen. bryg. janusza gąsiorowskiego': 'ŚRÓDMIEŚCIE',
  'gen. franciszka kleeberga': 'PÓŁNOC',
  'gen. henryka dembińskiego': 'TYSIĄCLECIE',
  'gen. ignacego prądzyńskiego': 'TYSIĄCLECIE',
  'gen. jakuba jasińskiego': 'CZĘSTOCHÓWKA-PARKITKA',
  'gen. jana skrzyneckiego': 'TYSIĄCLECIE',
  'gen. józefa bema': 'STRADOM',
  'gen. józefa chłopickiego': 'TYSIĄCLECIE',
  'gen. józefa hallera': 'ZAWODZIE-DĄBIE',
  'gen. józefa sowińskiego': 'TYSIĄCLECIE',
  'gen. józefa zajączka': 'TYSIĄCLECIE',
  'gen. karola kniaziewicza': 'TYSIĄCLECIE',
  'gen. kazimierza sosnkowskiego': 'PÓŁNOC',
  'gen. leopolda okulickiego': 'CZĘSTOCHÓWKA-PARKITKA',
  'gen. michała tokarzewskiego-karaszewicza': 'GRABÓWKA',
  'gen. mieczysława dąbkowskiego': 'ŚRÓDMIEŚCIE',
  'gen. stanisława maczka': 'PÓŁNOC',
  'gen. stanisława sosabowskiego': 'PÓŁNOC',
  'gen. tadeusza komorowskiego-bora': 'PÓŁNOC',
  'gen. tadeusza kutrzeby': 'PÓŁNOC',
  'gen. wilhelma orlik-rückemanna': 'ZAWODZIE-DĄBIE',
  'gen. władysława andersa': 'PÓŁNOC',
  geodetów: 'PÓŁNOC',
  gerberowa: 'KIEDRZYN',
  gerwazego: 'STRADOM',
  gilowa: 'ZAWODZIE-DĄBIE',
  'giuseppe garibaldiego': 'STARE MIASTO',
  giżycka: 'LISINIEC',
  glebowa: 'GNASZYN-KAWODRZA',
  glinowa: 'GNASZYN-KAWODRZA',
  gliwicka: 'LISINIEC',
  gminna: 'GRABÓWKA',
  gnaszyńska: 'PODJASNOGÓRSKA',
  gnieźnieńska: 'LISINIEC',
  goplany: 'ZAWODZIE-DĄBIE',
  gorzowska: 'LISINIEC',
  gościnna: 'DŹBÓW',
  goździków: 'GRABÓWKA',
  grafików: 'GNASZYN-KAWODRZA',
  graniczna: 'STARE MIASTO',
  granitowa: 'ZAWODZIE-DĄBIE',
  grażyny: 'DŹBÓW',
  'grażyny bacewicz': 'PÓŁNOC',
  grenadierów: 'STRADOM',
  grobla: 'BŁESZNO',
  gronowa: 'DŹBÓW',
  gruntowa: 'GRABÓWKA',
  grunwaldzka: 'PODJASNOGÓRSKA',
  gruszowa: 'KIEDRZYN',
  grzybowska: 'BŁESZNO',
  'guglielmo marconiego': 'CZĘSTOCHÓWKA-PARKITKA',
  'gustawa grackiego': 'DŹBÓW',
  'gustawa orlicz-dreszera': 'CZĘSTOCHÓWKA-PARKITKA',
  gwardzistów: 'STRADOM',
  gwiezdna: 'TYSIĄCLECIE',
  gwintowa: 'DŹBÓW',
  górki: 'OSTATNI GROSZ',
  górna: 'OSTATNI GROSZ',
  górników: 'ZAWODZIE-DĄBIE',
  górnośląska: 'LISINIEC',
  górska: 'OSTATNI GROSZ',
  gęsia: 'GNASZYN-KAWODRZA',
  gładka: 'ZAWODZIE-DĄBIE',
  głogowa: 'MIRÓW',
  główna: 'GNASZYN-KAWODRZA',
  głęboka: 'OSTATNI GROSZ',
  'haliny poświatowskiej': 'TYSIĄCLECIE',
  'hanny malewskiej': 'WYCZERPY-ANIOŁÓW',
  'hansa christiana andersena': 'RAKÓW',
  harcerska: 'STRADOM',
  harfowa: 'GNASZYN-KAWODRZA',
  hektarowa: 'MIRÓW',
  heleny: 'STRADOM',
  helska: 'GNASZYN-KAWODRZA',
  'henryka barona': 'CZĘSTOCHÓWKA-PARKITKA',
  'henryka jordana': 'GNASZYN-KAWODRZA',
  'henryka rodakowskiego': 'STRADOM',
  'henryka siemiradzkiego': 'STRADOM',
  'henryka wieniawskiego': 'STRADOM',
  henryki: 'PODJASNOGÓRSKA',
  heraklesa: 'GRABÓWKA',
  herbaciana: 'GNASZYN-KAWODRZA',
  herbska: 'PODJASNOGÓRSKA',
  'hetm. jana karola chodkiewicza': 'STRADOM',
  'hetm. jana tarnowskiego': 'STRADOM',
  'hetm. jana zamoyskiego': 'STRADOM',
  'hetm. stefana czarnieckiego': 'TYSIĄCLECIE',
  'hetm. stefana żółkiewskiego': 'STRADOM',
  hetmańska: 'STRADOM',
  hiacyntowa: 'PÓŁNOC',
  hodowlana: 'GNASZYN-KAWODRZA',
  horeszków: 'STRADOM',
  hoża: 'STRADOM',
  huculska: 'LISINIEC',
  husarska: 'STRADOM',
  hutników: 'ZAWODZIE-DĄBIE',
  iglasta: 'OSTATNI GROSZ',
  'ignacego kozielewskiego': 'TYSIĄCLECIE',
  'ignacego mościckiego': 'CZĘSTOCHÓWKA-PARKITKA',
  'ignacego paderewskiego': 'STRADOM',
  'ignacego łukasiewicza': 'WYCZERPY-ANIOŁÓW',
  ikara: 'GRABÓWKA',
  imbirowa: 'DŹBÓW',
  inowrocławska: 'LISINIEC',
  inspektowa: 'GNASZYN-KAWODRZA',
  'inwalidów wojennych': 'TYSIĄCLECIE',
  inżynieryjna: 'STRADOM',
  'ireny kosmowskiej': 'PÓŁNOC',
  irydowa: 'BŁESZNO',
  irysowa: 'GRABÓWKA',
  iławska: 'CZĘSTOCHÓWKA-PARKITKA',
  jabłonowa: 'GRABÓWKA',
  jachtowa: 'DŹBÓW',
  'jacka kaczmarskiego': 'PÓŁNOC',
  'jacka kuronia': 'KIEDRZYN',
  'jacka malczewskiego': 'STRADOM',
  jagienki: 'PODJASNOGÓRSKA',
  jagodowa: 'BŁESZNO',
  'jana andrzeja morsztyna': 'WYCZERPY-ANIOŁÓW',
  'jana brzechwy': 'TYSIĄCLECIE',
  'jana dzierżonia': 'GRABÓWKA',
  'jana gutenberga': 'WYCZERPY-ANIOŁÓW',
  'jana i jędrzeja śniadeckich': 'TRZECH WIESZCZÓW',
  'jana iii sobieskiego': 'TRZECH WIESZCZÓW',
  'jana karskiego': 'KIEDRZYN',
  'jana karłowicza': 'WYCZERPY-ANIOŁÓW',
  'jana kasprowicza': 'RAKÓW',
  'jana kiepury': 'GRABÓWKA',
  'jana kochanowskiego': 'ZAWODZIE-DĄBIE',
  'jana lechonia': 'WRZOSOWIAK',
  'jana matejki': 'STRADOM',
  'jana nowaka-jeziorańskiego': 'KIEDRZYN',
  'jana olbrachta': 'STRADOM',
  'jana parandowskiego': 'WYCZERPY-ANIOŁÓW',
  'jana pietrusińskiego': 'RAKÓW',
  'jana stanisława jankowskiego': 'PÓŁNOC',
  'janiny porazińskiej': 'WYCZERPY-ANIOŁÓW',
  jankiela: 'STRADOM',
  jantarowa: 'BŁESZNO',
  'janusza korczaka': 'TRZECH WIESZCZÓW',
  'janusza kusocińskiego': 'BŁESZNO',
  'jarosława iwaszkiewicza': 'PÓŁNOC',
  jarosławska: 'LISINIEC',
  jarzębinowa: 'KIEDRZYN',
  jaskrowska: 'STARE MIASTO',
  jaskółcza: 'ZAWODZIE-DĄBIE',
  jasna: 'ZAWODZIE-DĄBIE',
  jasnogórska: 'ŚRÓDMIEŚCIE',
  jastrzębia: 'ZAWODZIE-DĄBIE',
  jaworowa: 'GNASZYN-KAWODRZA',
  jazzowa: 'STRADOM',
  jałowcowa: 'GNASZYN-KAWODRZA',
  jeleniogórska: 'LISINIEC',
  jemiołowa: 'KIEDRZYN',
  'jerzego dudy gracza': 'GRABÓWKA',
  'jerzego kukuczki': 'PÓŁNOC',
  'jerzego lieberta': 'BŁESZNO',
  'jerzego szajnowicza-iwanowa': 'TYSIĄCLECIE',
  'jerzego szaniawskiego': 'WYCZERPY-ANIOŁÓW',
  'jerzego waszyngtona': 'ŚRÓDMIEŚCIE',
  jesienna: 'WRZOSOWIAK',
  jezioran: 'GNASZYN-KAWODRZA',
  jeżynowa: 'GNASZYN-KAWODRZA',
  'joachima lelewela': 'ŚRÓDMIEŚCIE',
  jowiszowa: 'CZĘSTOCHÓWKA-PARKITKA',
  'juliana fałata': 'STRADOM',
  'juliana kalinki': 'PÓŁNOC',
  'juliana krzyżanowskiego': 'BŁESZNO',
  'juliana tuwima': 'ŚRÓDMIEŚCIE',
  'juliana ursyna niemcewicza': 'WYCZERPY-ANIOŁÓW',
  'juliusza osterwy': 'WYCZERPY-ANIOŁÓW',
  'juliusza słowackiego': 'TRZECH WIESZCZÓW',
  junacka: 'GNASZYN-KAWODRZA',
  jurajska: 'ZAWODZIE-DĄBIE',
  juranda: 'STRADOM',
  jutowa: 'ZAWODZIE-DĄBIE',
  'józefa brandta': 'STRADOM',
  'józefa chełmońskiego': 'STRADOM',
  'józefa conrada-korzeniowskiego': 'WYCZERPY-ANIOŁÓW',
  'józefa czapskiego': 'WYCZERPY-ANIOŁÓW',
  'józefa czechowicza': 'WYCZERPY-ANIOŁÓW',
  'józefa gaczkowskiego': 'RAKÓW',
  'józefa ignacego kraszewskiego': 'WYCZERPY-ANIOŁÓW',
  'józefa lompy': 'PODJASNOGÓRSKA',
  'józefa maksymiliana ossolińskiego': 'WYCZERPY-ANIOŁÓW',
  'józefa marii hoene-wrońskiego': 'TRZECH WIESZCZÓW',
  'józefa mehoffera': 'STRADOM',
  'józefa mireckiego': 'RAKÓW',
  'józefa pankiewicza': 'WYCZERPY-ANIOŁÓW',
  'józefa parczyńskiego': 'KIEDRZYN',
  'józefa sułkowskiego': 'ŚRÓDMIEŚCIE',
  'józefa wybickiego': 'TYSIĄCLECIE',
  'józefa wójcickiego': 'PÓŁNOC',
  jęczmienna: 'BŁESZNO',
  jędrzejowska: 'CZĘSTOCHÓWKA-PARKITKA',
  kaczorowska: 'ZAWODZIE-DĄBIE',
  kadetów: 'STRADOM',
  kajakowa: 'DŹBÓW',
  kalinowa: 'GRABÓWKA',
  kaliska: 'LISINIEC',
  kamienna: 'ZAWODZIE-DĄBIE',
  'kanał kohna': 'STARE MIASTO',
  kanonierów: 'STRADOM',
  kaprys: 'DŹBÓW',
  kapucyńska: 'PODJASNOGÓRSKA',
  karkonoska: 'CZĘSTOCHÓWKA-PARKITKA',
  'karola dickensa': 'WYCZERPY-ANIOŁÓW',
  'karola irzykowskiego': 'RAKÓW',
  'karola miarki': 'WYCZERPY-ANIOŁÓW',
  'karola szajnochy': 'WYCZERPY-ANIOŁÓW',
  'karola szymanowskiego': 'ŚRÓDMIEŚCIE',
  karpacka: 'DŹBÓW',
  kartuska: 'LISINIEC',
  kasztanowa: 'WRZOSOWIAK',
  kaszubska: 'LISINIEC',
  katedralna: 'STARE MIASTO',
  kawalerzystów: 'STRADOM',
  kawia: 'STARE MIASTO',
  kawodrzańska: 'STRADOM',
  'kazimiery iłłakowiczówny': 'RAKÓW',
  'kazimierza knauera': 'STARE MIASTO',
  'kazimierza przerwy-tetmajera': 'RAKÓW',
  'kazimierza pużaka': 'PÓŁNOC',
  'kazimierza wielkiego': 'STRADOM',
  'kazimierza wierzyńskiego': 'TYSIĄCLECIE',
  ketlinga: 'STRADOM',
  kielecka: 'CZĘSTOCHÓWKA-PARKITKA',
  klasztorna: 'CZĘSTOCHÓWKA-PARKITKA',
  klonowa: 'KIEDRZYN',
  kluczborska: 'LISINIEC',
  kmicica: 'STRADOM',
  koksowa: 'ZAWODZIE-DĄBIE',
  kolarska: 'GRABÓWKA',
  kolejowa: 'BŁESZNO',
  kolorowa: 'GNASZYN-KAWODRZA',
  komandorska: 'STRADOM',
  komandosów: 'STRADOM',
  komornicka: 'MIRÓW',
  koniecpolska: 'LISINIEC',
  konińska: 'LISINIEC',
  'konstantego ildefonsa gałczyńskiego': 'TYSIĄCLECIE',
  konstruktorów: 'BŁESZNO',
  konwaliowa: 'STRADOM',
  kopalniana: 'DŹBÓW',
  kopcowa: 'ZAWODZIE-DĄBIE',
  korkowa: 'BŁESZNO',
  korzenna: 'DŹBÓW',
  kosiarzy: 'BŁESZNO',
  kosmiczna: 'TYSIĄCLECIE',
  kosynierska: 'STRADOM',
  koszalińska: 'LISINIEC',
  koszarowa: 'STRADOM',
  koszykowa: 'ZAWODZIE-DĄBIE',
  kosów: 'GRABÓWKA',
  kozia: 'STARE MIASTO',
  kołobrzeska: 'LISINIEC',
  kościelna: 'STRADOM',
  'kpt. jerzego kurpińskiego-ponurego': 'TYSIĄCLECIE',
  'kpt. leona sabatowskiego': 'WYCZERPY-ANIOŁÓW',
  'kpt. stanisława sojczyńskiego-warszyca': 'PÓŁNOC',
  krakowska: 'STARE MIASTO',
  krasińskiego: 'TRZECH WIESZCZÓW',
  krańcowa: 'MIRÓW',
  kredowa: 'GRABÓWKA',
  kresowa: 'WYCZERPY-ANIOŁÓW',
  krokusowa: 'KIEDRZYN',
  krośnieńska: 'LISINIEC',
  krucza: 'ZAWODZIE-DĄBIE',
  kruszwicka: 'LISINIEC',
  krynicka: 'CZĘSTOCHÓWKA-PARKITKA',
  krystyny: 'PODJASNOGÓRSKA',
  krzemienna: 'GRABÓWKA',
  krzepicka: 'LISINIEC',
  krzysi: 'STRADOM',
  'krzysztofa kamila baczyńskiego': 'PÓŁNOC',
  'krzysztofa komedy': 'GRABÓWKA',
  królewska: 'STRADOM',
  krótka: 'STARE MIASTO',
  kręta: 'OSTATNI GROSZ',
  'ks. biskupa franciszka musiela': 'KIEDRZYN',
  'ks. bonawentury metlera': 'PÓŁNOC',
  'ks. hugona kołłątaja': 'ZAWODZIE-DĄBIE',
  'ks. ignacego skorupki': 'RAKÓW',
  'ks. jana długosza': 'ZAWODZIE-DĄBIE',
  'ks. jerzego popiełuszki': 'ŚRÓDMIEŚCIE',
  'ks. józefa tischnera': 'KIEDRZYN',
  'ks. piotra skargi': 'WYCZERPY-ANIOŁÓW',
  'ks. piotra ściegiennego': 'WYCZERPY-ANIOŁÓW',
  'ks. stanisława brzóski': 'WYCZERPY-ANIOŁÓW',
  'ks. stanisława grochowskiego': 'TYSIĄCLECIE',
  'ks. stanisława konarskiego': 'WYCZERPY-ANIOŁÓW',
  'ks. stanisława staszica': 'ŚRÓDMIEŚCIE',
  'księcia adama jerzego czartoryskiego': 'TYSIĄCLECIE',
  'księcia jeremiego wiśniowieckiego': 'STRADOM',
  'księcia józefa poniatowskiego': 'STRADOM',
  'księcia leszka białego': 'STRADOM',
  'księdza wróblewskiego': 'STARE MIASTO',
  księżycowa: 'TYSIĄCLECIE',
  'kucelin łąki': 'ZAWODZIE-DĄBIE',
  kucelińska: 'ZAWODZIE-DĄBIE',
  kujawska: 'CZĘSTOCHÓWKA-PARKITKA',
  kusięcka: 'ZAWODZIE-DĄBIE',
  kutnowska: 'CZĘSTOCHÓWKA-PARKITKA',
  kwatermistrzów: 'STRADOM',
  kwiatowa: 'MIRÓW',
  kącik: 'OSTATNI GROSZ',
  kąkolowa: 'LISINIEC',
  kątna: 'ZAWODZIE-DĄBIE',
  kędzierzyńska: 'LISINIEC',
  kłobucka: 'LISINIEC',
  kłodzka: 'LISINIEC',
  kłomnicka: 'LISINIEC',
  lakowa: 'DŹBÓW',
  laurowa: 'DŹBÓW',
  lawendowa: 'KIEDRZYN',
  lazurowa: 'WYCZERPY-ANIOŁÓW',
  lednicka: 'LISINIEC',
  legendy: 'GNASZYN-KAWODRZA',
  legionów: 'ZAWODZIE-DĄBIE',
  legnicka: 'LISINIEC',
  'leona schillera': 'PÓŁNOC',
  'leona wyczółkowskiego': 'STRADOM',
  'leonida teligi': 'TYSIĄCLECIE',
  'leopolda staffa': 'WYCZERPY-ANIOŁÓW',
  leszczynowa: 'KIEDRZYN',
  letnia: 'BŁESZNO',
  letniskowa: 'BŁESZNO',
  leśna: 'DŹBÓW',
  ligii: 'GRABÓWKA',
  liliowa: 'KIEDRZYN',
  limanowska: 'LISINIEC',
  limbowa: 'WRZOSOWIAK',
  lipowa: 'WRZOSOWIAK',
  lirowa: 'GNASZYN-KAWODRZA',
  lisia: 'DŹBÓW',
  listonoszy: 'DŹBÓW',
  litewska: 'LISINIEC',
  lniana: 'GNASZYN-KAWODRZA',
  lodowa: 'DŹBÓW',
  'longina podbipięty': 'STRADOM',
  loretańska: 'PODJASNOGÓRSKA',
  lotników: 'STRADOM',
  lotosu: 'DŹBÓW',
  lourdyjska: 'WYCZERPY-ANIOŁÓW',
  luba: 'GRABÓWKA',
  lubelska: 'LISINIEC',
  lubliniecka: 'LISINIEC',
  lubuska: 'LISINIEC',
  'lucjana rydla': 'DŹBÓW',
  'lucjusza władysława cyganowskiego': 'WYCZERPY-ANIOŁÓW',
  'ludmiły marjańskiej': 'TYSIĄCLECIE',
  ludowa: 'KIEDRZYN',
  'ludwika krzywickiego': 'WYCZERPY-ANIOŁÓW',
  'ludwika mierosławskiego': 'KIEDRZYN',
  'ludwika pasteura': 'ZAWODZIE-DĄBIE',
  'ludwika solskiego': 'WYCZERPY-ANIOŁÓW',
  'ludwika trochimowskiego': 'ZAWODZIE-DĄBIE',
  'ludwika waryńskiego': 'RAKÓW',
  'ludwika wawrzynowicza': 'TYSIĄCLECIE',
  ludwiki: 'PODJASNOGÓRSKA',
  'luigi galwaniego': 'ZAWODZIE-DĄBIE',
  lustrzana: 'DŹBÓW',
  lutniowa: 'DŹBÓW',
  magiczna: 'GNASZYN-KAWODRZA',
  majowa: 'BŁESZNO',
  makietowa: 'DŹBÓW',
  makowa: 'LISINIEC',
  malborska: 'LISINIEC',
  malinowa: 'BŁESZNO',
  malownicza: 'DŹBÓW',
  manganowa: 'ZAWODZIE-DĄBIE',
  'marcina kasprzaka': 'TYSIĄCLECIE',
  'mariana michalika': 'WYCZERPY-ANIOŁÓW',
  'marii dąbrowskiej': 'RAKÓW',
  'marii konopnickiej': 'RAKÓW',
  'marii kownackiej': 'PÓŁNOC',
  'marii kuncewiczowej': 'RAKÓW',
  'marii pawlikowskiej-jasnorzewskiej': 'RAKÓW',
  'marii skłodowskiej-curie': 'TRZECH WIESZCZÓW',
  'mariusza bojemskiego': 'ZAWODZIE-DĄBIE',
  'marka hłaski': 'BŁESZNO',
  'marka perepeczki': 'ŚRÓDMIEŚCIE',
  marmurowa: 'ZAWODZIE-DĄBIE',
  marsowa: 'CZĘSTOCHÓWKA-PARKITKA',
  'marszałka edwarda rydza-śmigłego': 'WRZOSOWIAK',
  'marszałka ferdynanda focha': 'ŚRÓDMIEŚCIE',
  'marszałka józefa piłsudskiego': 'STARE MIASTO',
  marszałkowska: 'PÓŁNOC',
  'marynarki wojennej': 'STRADOM',
  marynarska: 'GNASZYN-KAWODRZA',
  marysia: 'ZAWODZIE-DĄBIE',
  'maurycego mochnackiego': 'RAKÓW',
  mazowiecka: 'CZĘSTOCHÓWKA-PARKITKA',
  mazurska: 'LISINIEC',
  mała: 'STARE MIASTO',
  'mała warszawka': 'GNASZYN-KAWODRZA',
  małopolska: 'CZĘSTOCHÓWKA-PARKITKA',
  'melchiora wańkowicza': 'PÓŁNOC',
  meliorantów: 'WYCZERPY-ANIOŁÓW',
  metalowców: 'ZAWODZIE-DĄBIE',
  michaliny: 'BŁESZNO',
  'michała bałuckiego': 'STRADOM',
  'michała brzeskiego': 'KIEDRZYN',
  'michała drzymały': 'DŹBÓW',
  'michała faradaya': 'ZAWODZIE-DĄBIE',
  'michała kleofasa ogińskiego': 'ŚRÓDMIEŚCIE',
  'michała lermontowa': 'WYCZERPY-ANIOŁÓW',
  'michała ossowskiego': 'RAKÓW',
  miechowska: 'LISINIEC',
  'mieczysława michałowicza': 'TYSIĄCLECIE',
  miedziana: 'ZAWODZIE-DĄBIE',
  mierna: 'ZAWODZIE-DĄBIE',
  'mieszka starego': 'STRADOM',
  migdałowa: 'KIEDRZYN',
  'mikołaja kopernika': 'ŚRÓDMIEŚCIE',
  'mikołaja reja': 'ZAWODZIE-DĄBIE',
  miniowa: 'GNASZYN-KAWODRZA',
  miodowa: 'BŁESZNO',
  'mirona białoszewskiego': 'WYCZERPY-ANIOŁÓW',
  mirtowa: 'DŹBÓW',
  miętowa: 'DŹBÓW',
  miła: 'ZAWODZIE-DĄBIE',
  'mjra henryka dobrzańskiego-hubala': 'PÓŁNOC',
  'mjra henryka sucharskiego': 'KIEDRZYN',
  'mjra waleriana łukasińskiego': 'RAKÓW',
  mleczna: 'GNASZYN-KAWODRZA',
  modra: 'GRABÓWKA',
  modrzewiowa: 'GNASZYN-KAWODRZA',
  mokra: 'STARE MIASTO',
  monterów: 'BŁESZNO',
  morenowa: 'MIRÓW',
  morska: 'MIRÓW',
  mostowa: 'STARE MIASTO',
  motyli: 'GNASZYN-KAWODRZA',
  mrągowska: 'LISINIEC',
  mstowska: 'MIRÓW',
  mundurowa: 'STRADOM',
  muszyńska: 'LISINIEC',
  muzealna: 'GNASZYN-KAWODRZA',
  myszkowska: 'LISINIEC',
  mączna: 'MIRÓW',
  młodości: 'KIEDRZYN',
  młynarska: 'WYCZERPY-ANIOŁÓW',
  'nad wartą': 'STARE MIASTO',
  nadrzeczna: 'STARE MIASTO',
  naftowa: 'LISINIEC',
  nagietkowa: 'KIEDRZYN',
  namysłowska: 'LISINIEC',
  narcyzowa: 'KIEDRZYN',
  nastrojowa: 'GNASZYN-KAWODRZA',
  nauczycielska: 'DŹBÓW',
  neptunowa: 'CZĘSTOCHÓWKA-PARKITKA',
  niecała: 'ZAWODZIE-DĄBIE',
  nieduża: 'DŹBÓW',
  niedługa: 'OSTATNI GROSZ',
  niewielka: 'OSTATNI GROSZ',
  niska: 'OSTATNI GROSZ',
  'norberta barlickiego': 'RAKÓW',
  nowa: 'OSTATNI GROSZ',
  nowobialska: 'CZĘSTOCHÓWKA-PARKITKA',
  nowosądecka: 'LISINIEC',
  nowotarska: 'LISINIEC',
  nyska: 'CZĘSTOCHÓWKA-PARKITKA',
  'o. augustyna kordeckiego': 'PODJASNOGÓRSKA',
  objazdowa: 'GNASZYN-KAWODRZA',
  'obrońców poczty gdańskiej': 'TYSIĄCLECIE',
  'obrońców westerplatte': 'TYSIĄCLECIE',
  odlewników: 'ZAWODZIE-DĄBIE',
  odrodzenia: 'GRABÓWKA',
  odrzańska: 'ZAWODZIE-DĄBIE',
  oficerska: 'STRADOM',
  ogrodowa: 'STARE MIASTO',
  okrętowa: 'DŹBÓW',
  okrężna: 'GNASZYN-KAWODRZA',
  okólna: 'TYSIĄCLECIE',
  oleńki: 'PODJASNOGÓRSKA',
  'olgi boznańskiej': 'STRADOM',
  olkuska: 'LISINIEC',
  olszowa: 'WRZOSOWIAK',
  olsztyńska: 'ZAWODZIE-DĄBIE',
  opoczyńska: 'LISINIEC',
  opolska: 'CZĘSTOCHÓWKA-PARKITKA',
  orawska: 'LISINIEC',
  orla: 'ZAWODZIE-DĄBIE',
  orzechowa: 'GNASZYN-KAWODRZA',
  'osada młyńska': 'GNASZYN-KAWODRZA',
  osikowa: 'WRZOSOWIAK',
  ostatnia: 'DŹBÓW',
  ostra: 'OSTATNI GROSZ',
  ostrowska: 'LISINIEC',
  ostrołęcka: 'LISINIEC',
  owcza: 'BŁESZNO',
  owocowa: 'KIEDRZYN',
  owsiana: 'BŁESZNO',
  ozonowa: 'DŹBÓW',
  oławska: 'CZĘSTOCHÓWKA-PARKITKA',
  ołowiana: 'ZAWODZIE-DĄBIE',
  oświęcimska: 'LISINIEC',
  pabianicka: 'CZĘSTOCHÓWKA-PARKITKA',
  pajęcza: 'WYCZERPY-ANIOŁÓW',
  palladowa: 'ZAWODZIE-DĄBIE',
  palmowa: 'WRZOSOWIAK',
  'pana tadeusza': 'STRADOM',
  pancerna: 'STRADOM',
  papierowa: 'ZAWODZIE-DĄBIE',
  'park 3 maja': 'PODJASNOGÓRSKA',
  'park staszica': 'PODJASNOGÓRSKA',
  partyzantów: 'ŚRÓDMIEŚCIE',
  'pasaż biskupa bareły': 'PODJASNOGÓRSKA',
  'pasaż opolczyka': 'ŚRÓDMIEŚCIE',
  'pasaż raczyńskich': 'RAKÓW',
  'pasaż stasieckiego': 'CZĘSTOCHÓWKA-PARKITKA',
  pastelowa: 'STRADOM',
  pawia: 'GRABÓWKA',
  'pawła jasienicy': 'RAKÓW',
  piaskowa: 'ZAWODZIE-DĄBIE',
  piastowska: 'STRADOM',
  piechoty: 'STRADOM',
  pienińska: 'LISINIEC',
  pilotów: 'STRADOM',
  pionierów: 'STRADOM',
  'piotra bardowskiego': 'OSTATNI GROSZ',
  'piotra czajkowskiego': 'DŹBÓW',
  'piotra wysockiego': 'CZĘSTOCHÓWKA-PARKITKA',
  piotrkowska: 'STARE MIASTO',
  pirotechników: 'STRADOM',
  'piusa welońskiego': 'WYCZERPY-ANIOŁÓW',
  piękna: 'BŁESZNO',
  'plac armstronga': 'STARE MIASTO',
  'plac biegańskiego': 'ŚRÓDMIEŚCIE',
  'plac bohaterów getta': 'STARE MIASTO',
  'plac ignacego daszyńskiego': 'STARE MIASTO',
  'plac katyński': 'STARE MIASTO',
  'plac orląt lwowskix': 'RAKÓW',
  'plac pamięci narodowej': 'ŚRÓDMIEŚCIE',
  'plac papieża jana pawła ii': 'STARE MIASTO',
  'plac rady europy': 'ŚRÓDMIEŚCIE',
  'plac walecznych': 'DŹBÓW',
  'plac willengerga': 'STARE MIASTO',
  platynowa: 'GNASZYN-KAWODRZA',
  plażowa: 'DŹBÓW',
  podbiałowa: 'GNASZYN-KAWODRZA',
  podbucze: 'WRZOSOWIAK',
  podchorążych: 'STRADOM',
  podgórna: 'GRABÓWKA',
  podhalańska: 'LISINIEC',
  podkolejowa: 'STRADOM',
  podkomorzego: 'STRADOM',
  podlaska: 'LISINIEC',
  podmiejska: 'STRADOM',
  podmokła: 'ZAWODZIE-DĄBIE',
  podolska: 'LISINIEC',
  podwale: 'ZAWODZIE-DĄBIE',
  podwójna: 'ZAWODZIE-DĄBIE',
  pogodna: 'ZAWODZIE-DĄBIE',
  poleska: 'CZĘSTOCHÓWKA-PARKITKA',
  polna: 'STRADOM',
  'polskiego czerwonego krzyża': 'TYSIĄCLECIE',
  'polskiej organizacji wojskowej': 'ŚRÓDMIEŚCIE',
  pomorska: 'LISINIEC',
  'por. hieronima dudwała': 'PÓŁNOC',
  portowa: 'DŹBÓW',
  poręba: 'BŁESZNO',
  poselska: 'BŁESZNO',
  powały: 'STRADOM',
  powstańców: 'STRADOM',
  'powstańców warszawy': 'DŹBÓW',
  'powstańców śląskich': 'OSTATNI GROSZ',
  poziomkowa: 'BŁESZNO',
  poznańska: 'LISINIEC',
  połaniecka: 'WYCZERPY-ANIOŁÓW',
  południowa: 'WRZOSOWIAK',
  'ppłk. zygmunta żywockiego': 'WYCZERPY-ANIOŁÓW',
  'prof. aleksandra brücknera': 'WYCZERPY-ANIOŁÓW',
  'prof. czesława kameli': 'PÓŁNOC',
  'prof. edwarda warchałowskiego': 'PÓŁNOC',
  'prof. edwarda wittiga': 'WYCZERPY-ANIOŁÓW',
  'prof. janusza witolda elsnera': 'TYSIĄCLECIE',
  'prof. jerzego gomoliszewskiego': 'PÓŁNOC',
  'prof. jerzego kołakowskiego': 'TYSIĄCLECIE',
  'prof. józefa nusbauma': 'WYCZERPY-ANIOŁÓW',
  'prof. kaspra weigla': 'PÓŁNOC',
  'prof. kazimierza michałowskiego': 'PÓŁNOC',
  'prof. kazimierza zarankiewicza': 'WYCZERPY-ANIOŁÓW',
  'prof. marcelego nenckiego': 'WYCZERPY-ANIOŁÓW',
  'prof. mariana piaseckiego': 'PÓŁNOC',
  'prof. stanisława kontkiewicza': 'WYCZERPY-ANIOŁÓW',
  'prof. stefana banacha': 'PÓŁNOC',
  'prof. stefana hausbrandta': 'PÓŁNOC',
  'prof. tadeusza kochmańskiego': 'PÓŁNOC',
  'prof. zygmunta kowalczyka': 'PÓŁNOC',
  'promenada niemena': 'TYSIĄCLECIE',
  'promenada olgi aleksandry sipowicz-kory': 'TRZECH WIESZCZÓW',
  promowa: 'DŹBÓW',
  prosta: 'OSTATNI GROSZ',
  protazego: 'STRADOM',
  przechodnia: 'STARE MIASTO',
  przejazdowa: 'GNASZYN-KAWODRZA',
  przelotna: 'GNASZYN-KAWODRZA',
  przemyska: 'LISINIEC',
  przemysłowa: 'STARE MIASTO',
  przesmyk: 'STARE MIASTO',
  przyjemna: 'DŹBÓW',
  próżna: 'ZAWODZIE-DĄBIE',
  prędziszów: 'MIRÓW',
  pszenna: 'BŁESZNO',
  ptasia: 'STARE MIASTO',
  pusta: 'OSTATNI GROSZ',
  północna: 'KIEDRZYN',
  'płk. marcina borelowskiego': 'TYSIĄCLECIE',
  płocka: 'LISINIEC',
  raciborska: 'LISINIEC',
  racławicka: 'ŚRÓDMIEŚCIE',
  radomska: 'GRABÓWKA',
  rajska: 'ZAWODZIE-DĄBIE',
  rakowska: 'WRZOSOWIAK',
  'reduty częstochowskiej': 'STRADOM',
  rejenta: 'STRADOM',
  rezerwistów: 'STRADOM',
  robotnicza: 'BŁESZNO',
  rolnicza: 'TYSIĄCLECIE',
  'romana dmowskiego': 'PÓŁNOC',
  'romualda mielczarskiego': 'STARE MIASTO',
  'roweckiego-grota': 'PÓŁNOC',
  rozdolna: 'MIRÓW',
  rozmarynowa: 'GNASZYN-KAWODRZA',
  'rtm. witolda pileckiego': 'PÓŁNOC',
  rudnicka: 'LISINIEC',
  rudziana: 'ZAWODZIE-DĄBIE',
  rumiankowa: 'GNASZYN-KAWODRZA',
  ruska: 'LISINIEC',
  rybacka: 'GRABÓWKA',
  rybna: 'ZAWODZIE-DĄBIE',
  rybnicka: 'LISINIEC',
  rycerska: 'STRADOM',
  'rynek prezydenta rp gabriela narutowicza': 'ZAWODZIE-DĄBIE',
  'rynek wieluński': 'CZĘSTOCHÓWKA-PARKITKA',
  'ryszarda wagnera': 'PODJASNOGÓRSKA',
  rzeczna: 'DŹBÓW',
  rzemieślnicza: 'ZAWODZIE-DĄBIE',
  rzepakowa: 'GNASZYN-KAWODRZA',
  rzeszowska: 'LISINIEC',
  rzeźnicka: 'OSTATNI GROSZ',
  rząsawska: 'WYCZERPY-ANIOŁÓW',
  rzędziana: 'STRADOM',
  równa: 'OSTATNI GROSZ',
  równoległa: 'OSTATNI GROSZ',
  różana: 'BŁESZNO',
  rędzińska: 'WYCZERPY-ANIOŁÓW',
  sabinowska: 'STRADOM',
  sadowa: 'WRZOSOWIAK',
  sandomierska: 'LISINIEC',
  sanocka: 'LISINIEC',
  saperów: 'STRADOM',
  sasankowa: 'WYCZERPY-ANIOŁÓW',
  sejmowa: 'KIEDRZYN',
  senatorska: 'STARE MIASTO',
  'seweryna goszczyńskiego': 'TRZECH WIESZCZÓW',
  siedlecka: 'LISINIEC',
  sieradzka: 'LISINIEC',
  sierpowa: 'DŹBÓW',
  skalna: 'MIRÓW',
  skarpowa: 'MIRÓW',
  skierniewicka: 'LISINIEC',
  skośna: 'OSTATNI GROSZ',
  skrzetuskiego: 'STRADOM',
  skrzypowa: 'DŹBÓW',
  'skwer dobosza': 'RAKÓW',
  'skwer gniatkowskiego': 'TYSIĄCLECIE',
  'skwer junaków': 'RAKÓW',
  'skwer kaliny jędrusik': 'TYSIĄCLECIE',
  'skwer lotników': 'ZAWODZIE-DĄBIE',
  'skwer religi': 'PODJASNOGÓRSKA',
  'skwer sokołów': 'TRZECH WIESZCZÓW',
  'skwer solidarności': 'ŚRÓDMIEŚCIE',
  'skwer sybiraków': 'TRZECH WIESZCZÓW',
  'skwer łęskiego': 'PODJASNOGÓRSKA',
  skwerowa: 'GRABÓWKA',
  smolna: 'BŁESZNO',
  solna: 'WYCZERPY-ANIOŁÓW',
  soplicy: 'STRADOM',
  sopocka: 'LISINIEC',
  sosnowa: 'OSTATNI GROSZ',
  sosnowiecka: 'LISINIEC',
  sowia: 'ZAWODZIE-DĄBIE',
  spacerowa: 'RAKÓW',
  spadek: 'STARE MIASTO',
  spadochroniarzy: 'STRADOM',
  spadzista: 'OSTATNI GROSZ',
  spartakusa: 'GRABÓWKA',
  spartańska: 'GRABÓWKA',
  spiska: 'LISINIEC',
  spokojna: 'ZAWODZIE-DĄBIE',
  sporna: 'ZAWODZIE-DĄBIE',
  sportowa: 'WRZOSOWIAK',
  społeczna: 'GNASZYN-KAWODRZA',
  spółdzielczości: 'GNASZYN-KAWODRZA',
  srebrna: 'ZAWODZIE-DĄBIE',
  stalowa: 'ZAWODZIE-DĄBIE',
  'stanisława dubois': 'TYSIĄCLECIE',
  'stanisława grochowiaka': 'WYCZERPY-ANIOŁÓW',
  'stanisława ignacego witkiewicza': 'RAKÓW',
  'stanisława kunickiego': 'RAKÓW',
  'stanisława marusarza': 'WRZOSOWIAK',
  'stanisława małachowskiego': 'ŚRÓDMIEŚCIE',
  'stanisława moniuszki': 'STRADOM',
  'stanisława orzechowskiego': 'ŚRÓDMIEŚCIE',
  'stanisława przybyszewskiego': 'RAKÓW',
  'stanisława wodzickiego': 'TYSIĄCLECIE',
  'stanisława worcella': 'TYSIĄCLECIE',
  'stanisława wyspiańskiego': 'RAKÓW',
  stanisławy: 'PODJASNOGÓRSKA',
  stara: 'CZĘSTOCHÓWKA-PARKITKA',
  starogardzka: 'LISINIEC',
  staropolska: 'CZĘSTOCHÓWKA-PARKITKA',
  'stary rynek': 'STARE MIASTO',
  stawowa: 'STARE MIASTO',
  'stefana batorego': 'STRADOM',
  'stefana jaracza': 'ŚRÓDMIEŚCIE',
  'stefana okrzei': 'RAKÓW',
  'stefana starzyńskiego': 'PÓŁNOC',
  'stefana żeromskiego': 'ZAWODZIE-DĄBIE',
  'stefanii sempołowskiej': 'RAKÓW',
  sternicza: 'BŁESZNO',
  stokrotkowa: 'KIEDRZYN',
  storczykowa: 'KIEDRZYN',
  strażacka: 'STARE MIASTO',
  strefowa: 'ZAWODZIE-DĄBIE',
  stroma: 'OSTATNI GROSZ',
  strumykowa: 'WYCZERPY-ANIOŁÓW',
  strzelecka: 'STRADOM',
  sucha: 'ZAWODZIE-DĄBIE',
  sudecka: 'LISINIEC',
  suwalska: 'LISINIEC',
  'syna pułku': 'STRADOM',
  szafranowa: 'KIEDRZYN',
  szamotowa: 'GNASZYN-KAWODRZA',
  szara: 'ZAWODZIE-DĄBIE',
  'szarych szeregów': 'BŁESZNO',
  szałwiowa: 'DŹBÓW',
  szczecińska: 'LISINIEC',
  szczytowa: 'OSTATNI GROSZ',
  szeroka: 'BŁESZNO',
  szklana: 'DŹBÓW',
  szkolna: 'BŁESZNO',
  'szlak królewski': 'BŁESZNO',
  szpakowa: 'ZAWODZIE-DĄBIE',
  szparagowa: 'GNASZYN-KAWODRZA',
  szpitalna: 'ZAWODZIE-DĄBIE',
  sztabowa: 'STRADOM',
  sztormowa: 'STRADOM',
  szybowa: 'GNASZYN-KAWODRZA',
  szydłowska: 'LISINIEC',
  'szymona klonowicza': 'PÓŁNOC',
  'szymona zimorowicza': 'ŚRÓDMIEŚCIE',
  sąsiedzka: 'WYCZERPY-ANIOŁÓW',
  sępowa: 'GNASZYN-KAWODRZA',
  słoneczna: 'ZAWODZIE-DĄBIE',
  słonecznikowa: 'KIEDRZYN',
  słowiańska: 'STRADOM',
  słowicza: 'ZAWODZIE-DĄBIE',
  słupska: 'LISINIEC',
  'tadeusza banachiewicza': 'WYCZERPY-ANIOŁÓW',
  'tadeusza boya-żeleńskiego': 'TRZECH WIESZCZÓW',
  'tadeusza brezy': 'TYSIĄCLECIE',
  'tadeusza gajcego': 'PÓŁNOC',
  'tadeusza kościuszki': 'ŚRÓDMIEŚCIE',
  'tadeusza mazowieckiego': 'KIEDRZYN',
  'tadeusza rejtana': 'ZAWODZIE-DĄBIE',
  'tadeusza więckowskiego': 'TYSIĄCLECIE',
  'tajnej organizacji nauczycielskiej': 'BŁESZNO',
  targowa: 'STARE MIASTO',
  tarnobrzeska: 'LISINIEC',
  tarnowska: 'LISINIEC',
  tartakowa: 'STARE MIASTO',
  tczewska: 'LISINIEC',
  telimeny: 'STRADOM',
  tenisowa: 'WYCZERPY-ANIOŁÓW',
  'teodora axentowicza': 'STRADOM',
  'teofila lenartowicza': 'RAKÓW',
  'teresy weyssenhoff': 'BŁESZNO',
  tkacka: 'ZAWODZIE-DĄBIE',
  'tomasza edisona': 'ZAWODZIE-DĄBIE',
  'tomasza wilsona': 'STARE MIASTO',
  'tomasza zana': 'TRZECH WIESZCZÓW',
  tomaszowska: 'LISINIEC',
  topolowa: 'WRZOSOWIAK',
  torowa: 'GNASZYN-KAWODRZA',
  toruńska: 'LISINIEC',
  towarowa: 'BŁESZNO',
  traktorzystów: 'WYCZERPY-ANIOŁÓW',
  trawowa: 'GNASZYN-KAWODRZA',
  trzcinowa: 'DŹBÓW',
  tucholska: 'LISINIEC',
  tulipanowa: 'KIEDRZYN',
  turbinowa: 'BŁESZNO',
  turkusowa: 'GNASZYN-KAWODRZA',
  turoszowska: 'LISINIEC',
  turystyczna: 'MIRÓW',
  twarda: 'OSTATNI GROSZ',
  tymczasowa: 'ZAWODZIE-DĄBIE',
  tymiankowa: 'DŹBÓW',
  tęczowa: 'GRABÓWKA',
  uczniowska: 'GNASZYN-KAWODRZA',
  ugody: 'WYCZERPY-ANIOŁÓW',
  ukryta: 'GRABÓWKA',
  urocza: 'GNASZYN-KAWODRZA',
  uzdrowiskowa: 'DŹBÓW',
  ułańska: 'STRADOM',
  'wacława berenta': 'WYCZERPY-ANIOŁÓW',
  'wacława nałkowskiego': 'WYCZERPY-ANIOŁÓW',
  'wacława sieroszewskiego': 'RAKÓW',
  'wacława tokarza': 'BŁESZNO',
  wadowicka: 'LISINIEC',
  wakacyjna: 'BŁESZNO',
  walcowników: 'BŁESZNO',
  'walerego wróblewskiego': 'TYSIĄCLECIE',
  wandy: 'PODJASNOGÓRSKA',
  'wandy rutkiewicz': 'WRZOSOWIAK',
  'wandy wereszczyńskiej': 'STRADOM',
  wapienna: 'ZAWODZIE-DĄBIE',
  warmińska: 'LISINIEC',
  warowna: 'GNASZYN-KAWODRZA',
  warzywna: 'BŁESZNO',
  wawelska: 'STRADOM',
  wazów: 'STRADOM',
  wałbrzyska: 'LISINIEC',
  wałowa: 'LISINIEC',
  wczasowa: 'BŁESZNO',
  wejherowska: 'LISINIEC',
  wesoła: 'ZAWODZIE-DĄBIE',
  weteranów: 'STRADOM',
  wełniana: 'ZAWODZIE-DĄBIE',
  wiatrakowa: 'BŁESZNO',
  widna: 'ZAWODZIE-DĄBIE',
  widłaków: 'WYCZERPY-ANIOŁÓW',
  wiejska: 'MIRÓW',
  wielkoborska: 'LISINIEC',
  wielkopiecowa: 'ZAWODZIE-DĄBIE',
  wielkopolska: 'CZĘSTOCHÓWKA-PARKITKA',
  wieluńska: 'CZĘSTOCHÓWKA-PARKITKA',
  wierchów: 'BŁESZNO',
  wierzbowa: 'WRZOSOWIAK',
  wieszczów: 'GNASZYN-KAWODRZA',
  wigoniowa: 'GNASZYN-KAWODRZA',
  wiklinowa: 'ZAWODZIE-DĄBIE',
  wilcza: 'BŁESZNO',
  wileńska: 'LISINIEC',
  wilgotna: 'ZAWODZIE-DĄBIE',
  wilgowa: 'DŹBÓW',
  'wilhelma roentgena': 'ZAWODZIE-DĄBIE',
  'wincentego pola': 'WYCZERPY-ANIOŁÓW',
  'wincentego rapackiego': 'RAKÓW',
  'wincentego witosa': 'PÓŁNOC',
  winicjusza: 'GRABÓWKA',
  wiolinowa: 'GRABÓWKA',
  wiosenna: 'TYSIĄCLECIE',
  wioślarska: 'ZAWODZIE-DĄBIE',
  wirażowa: 'BŁESZNO',
  'wisławy szymborskiej': 'KIEDRZYN',
  witaminowa: 'BŁESZNO',
  'witolda gombrowicza': 'PÓŁNOC',
  'witolda pruszkowskiego': 'STRADOM',
  wiązowa: 'WRZOSOWIAK',
  wiślana: 'ZAWODZIE-DĄBIE',
  wiśniowa: 'WRZOSOWIAK',
  wodociągowa: 'MIRÓW',
  wodzisławska: 'CZĘSTOCHÓWKA-PARKITKA',
  'wojciecha bogusławskiego': 'GNASZYN-KAWODRZA',
  'wojciecha gersona': 'STRADOM',
  'wojciecha korfantego': 'ZAWODZIE-DĄBIE',
  'wojciecha kossaka': 'STRADOM',
  'wojciecha łukaszewskiego': 'PÓŁNOC',
  wojskiego: 'STRADOM',
  wojskowa: 'STRADOM',
  'wolfganga amadeusza mozarta': 'PODJASNOGÓRSKA',
  wolna: 'ZAWODZIE-DĄBIE',
  wopistów: 'DŹBÓW',
  wołodyjowskiego: 'STRADOM',
  wołyńska: 'LISINIEC',
  wrocławska: 'CZĘSTOCHÓWKA-PARKITKA',
  wronia: 'GNASZYN-KAWODRZA',
  wrzosowa: 'BŁESZNO',
  wręczycka: 'LISINIEC',
  wspólna: 'ZAWODZIE-DĄBIE',
  wygodna: 'GNASZYN-KAWODRZA',
  wypalanki: 'BŁESZNO',
  wypoczynku: 'WYCZERPY-ANIOŁÓW',
  wysoka: 'OSTATNI GROSZ',
  wyzwolenia: 'PÓŁNOC',
  wąska: 'ZAWODZIE-DĄBIE',
  'władysława bartoszewskiego': 'KIEDRZYN',
  'władysława broniewskiego': 'TYSIĄCLECIE',
  'władysława daniłowskiego': 'RAKÓW',
  'władysława jagiełły': 'STRADOM',
  'władysława orkana': 'WRZOSOWIAK',
  'władysława podkowińskiego': 'STRADOM',
  'władysława reymonta': 'ZAWODZIE-DĄBIE',
  'władysława rudlickiego': 'PÓŁNOC',
  'władysława sebyły': 'RAKÓW',
  'władysława skoczylasa': 'STRADOM',
  'władysława syrokomli': 'RAKÓW',
  'władysława tatarkiewicza': 'WYCZERPY-ANIOŁÓW',
  'władysława warneńczyka': 'STRADOM',
  'władysława łokietka': 'STRADOM',
  władysławy: 'PODJASNOGÓRSKA',
  włodawska: 'CZĘSTOCHÓWKA-PARKITKA',
  'włodzimierza zagórskiego': 'WRZOSOWIAK',
  włoszczowska: 'LISINIEC',
  'xawerego dunikowskiego': 'TRZECH WIESZCZÓW',
  zabrzańska: 'LISINIEC',
  zaciszna: 'ZAWODZIE-DĄBIE',
  zagłoby: 'STRADOM',
  zakopiańska: 'GRABÓWKA',
  zamiejska: 'STRADOM',
  zatokowa: 'GRABÓWKA',
  'zaułek wieluński': 'CZĘSTOCHÓWKA-PARKITKA',
  zawierciańska: 'LISINIEC',
  zawilcowa: 'WYCZERPY-ANIOŁÓW',
  zawiszy: 'STRADOM',
  zawiła: 'ZAWODZIE-DĄBIE',
  zawodziańska: 'MIRÓW',
  załogi: 'BŁESZNO',
  zbawiciela: 'GNASZYN-KAWODRZA',
  'zbigniewa herberta': 'PÓŁNOC',
  zbyszka: 'STRADOM',
  zdrojowa: 'WYCZERPY-ANIOŁÓW',
  zdrowa: 'DŹBÓW',
  zegarowa: 'DŹBÓW',
  'zenona klemensiewicza': 'TYSIĄCLECIE',
  'zesłańców sybiru': 'WRZOSOWIAK',
  zgody: 'PODJASNOGÓRSKA',
  zgorzelecka: 'CZĘSTOCHÓWKA-PARKITKA',
  zielna: 'WYCZERPY-ANIOŁÓW',
  zielona: 'WRZOSOWIAK',
  zielonogórska: 'LISINIEC',
  zimowa: 'WRZOSOWIAK',
  'zofii kossak-szczuckiej': 'ŚRÓDMIEŚCIE',
  'zofii martusewicz': 'PÓŁNOC',
  'zofii nałkowskiej': 'TYSIĄCLECIE',
  'zofii stryjeńskiej': 'ŚRÓDMIEŚCIE',
  zosi: 'STRADOM',
  zuchów: 'BŁESZNO',
  zwycięzców: 'ŚRÓDMIEŚCIE',
  'zygmunta glogera': 'ŚRÓDMIEŚCIE',
  'zygmunta noskowskiego': 'PODJASNOGÓRSKA',
  złota: 'ZAWODZIE-DĄBIE',
  złotogórska: 'ZAWODZIE-DĄBIE',
  ładna: 'ZAWODZIE-DĄBIE',
  łanowa: 'ZAWODZIE-DĄBIE',
  łopianowa: 'GNASZYN-KAWODRZA',
  łosiowa: 'DŹBÓW',
  łowicka: 'CZĘSTOCHÓWKA-PARKITKA',
  łubinowa: 'STRADOM',
  łubińska: 'LISINIEC',
  łuczników: 'STRADOM',
  łukowa: 'GNASZYN-KAWODRZA',
  łużycka: 'LISINIEC',
  łódzka: 'CZĘSTOCHÓWKA-PARKITKA',
  łączności: 'STRADOM',
  łąkowa: 'WRZOSOWIAK',
  łęczycka: 'LISINIEC',
  ślepa: 'ZAWODZIE-DĄBIE',
  śliska: 'ZAWODZIE-DĄBIE',
  śląska: 'ŚRÓDMIEŚCIE',
  śnieżna: 'BŁESZNO',
  średnia: 'GRABÓWKA',
  'św. andrzeja': 'PODJASNOGÓRSKA',
  'św. anny': 'PODJASNOGÓRSKA',
  'św. augustyna': 'PODJASNOGÓRSKA',
  'św. barbary': 'PODJASNOGÓRSKA',
  'św. brata alberta': 'PÓŁNOC',
  'św. elżbiety': 'PODJASNOGÓRSKA',
  'św. faustyny': 'CZĘSTOCHÓWKA-PARKITKA',
  'św. franciszka': 'PODJASNOGÓRSKA',
  'św. jacka': 'PODJASNOGÓRSKA',
  'św. jana': 'CZĘSTOCHÓWKA-PARKITKA',
  'św. jana kantego': 'PODJASNOGÓRSKA',
  'św. jozafata': 'GNASZYN-KAWODRZA',
  'św. kaspra del bufalo': 'GRABÓWKA',
  'św. kazimierza': 'PODJASNOGÓRSKA',
  'św. kingi': 'PODJASNOGÓRSKA',
  'św. krzysztofa': 'CZĘSTOCHÓWKA-PARKITKA',
  'św. marka': 'PODJASNOGÓRSKA',
  'św. moniki': 'PODJASNOGÓRSKA',
  'św. pawła': 'GRABÓWKA',
  'św. piotra': 'PODJASNOGÓRSKA',
  'św. teresy': 'PODJASNOGÓRSKA',
  'św. wincentego pallottiego': 'PODJASNOGÓRSKA',
  'św. łukasza': 'PODJASNOGÓRSKA',
  świerczaki: 'BŁESZNO',
  świerkowa: 'DŹBÓW',
  świtezianki: 'DŹBÓW',
  świętokrzyska: 'CZĘSTOCHÓWKA-PARKITKA',
  źródlana: 'WRZOSOWIAK',
  żabia: 'ZAWODZIE-DĄBIE',
  żeglarska: 'DŹBÓW',
  żelazna: 'ZAWODZIE-DĄBIE',
  żonkilowa: 'KIEDRZYN',
  żołnierska: 'STRADOM',
  'żołnierzy niezłomnych': 'TYSIĄCLECIE',
  żurawia: 'GRABÓWKA',
  żurawinowa: 'DŹBÓW',
  żuławska: 'LISINIEC',
  żużlowa: 'ZAWODZIE-DĄBIE',
  żwirowa: 'ZAWODZIE-DĄBIE',
  żyrardowska: 'LISINIEC',
  żytnia: 'ZAWODZIE-DĄBIE',
  żywiecka: 'LISINIEC',
  żywopłotowa: 'DŹBÓW',
  żyzna: 'BŁESZNO',
};

const STREET_PREFIXES = [
  'ulica',
  'ul.',
  'ul',
  'aleja',
  'al.',
  'al',
  'osiedle',
  'os.',
  'os',
  'plac',
  'pl.',
  'pl',
  'skwer',
  'skw.',
  'rondo',
];

const STREET_ALIASES: Record<string, string> = {
  nmp: 'najswietszej maryi panny',
};

const CYRILLIC_TO_LATIN: Record<string, string> = {
  А: 'A',
  а: 'a',
  Б: 'B',
  б: 'b',
  В: 'V',
  в: 'v',
  Г: 'G',
  г: 'g',
  Д: 'D',
  д: 'd',
  Е: 'E',
  е: 'e',
  Ё: 'E',
  ё: 'e',
  Ж: 'Ż',
  ж: 'ż',
  З: 'Z',
  з: 'z',
  И: 'I',
  и: 'i',
  Й: 'J',
  й: 'j',
  К: 'K',
  к: 'k',
  Л: 'L',
  л: 'l',
  М: 'M',
  м: 'm',
  Н: 'N',
  н: 'n',
  О: 'O',
  о: 'o',
  П: 'P',
  п: 'p',
  Р: 'R',
  р: 'r',
  С: 'S',
  с: 's',
  Т: 'T',
  т: 't',
  У: 'U',
  у: 'u',
  Ф: 'F',
  ф: 'f',
  Х: 'X',
  х: 'x',
  Ц: 'C',
  ц: 'c',
  Ч: 'Ch',
  ч: 'ch',
  Ш: 'Sz',
  ш: 'sz',
  Щ: 'Ś',
  щ: 'ś',
  Ы: 'Y',
  ы: 'y',
  Э: 'E',
  э: 'e',
  Ю: 'Ju',
  ю: 'ju',
  Я: 'Ja',
  я: 'ja',
  І: 'I',
  і: 'i',
  Ї: 'I',
  ї: 'i',
};

function replaceCyrillicCharacters(value: string): string {
  return value.replace(
    /[А-Яа-яІЇЁЮЯ]/g,
    char => CYRILLIC_TO_LATIN[char] ?? char
  );
}

function stripDiacritics(value: string): string {
  return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

function normalizeStreetKey(raw: string | null | undefined): string | null {
  if (!raw) {
    return null;
  }
  let normalized = replaceCyrillicCharacters(raw)
    .replace(/ /g, ' ')
    .trim()
    .toLowerCase();
  if (!normalized) {
    return null;
  }
  normalized = stripDiacritics(normalized);
  normalized = normalized.replace(/[.,]/g, ' ');
  let prefixRemoved = true;
  while (prefixRemoved && normalized) {
    prefixRemoved = false;
    for (const prefix of STREET_PREFIXES) {
      if (
        normalized.startsWith(prefix) &&
        (normalized.length === prefix.length ||
          normalized[prefix.length] === ' ')
      ) {
        normalized = normalized.slice(prefix.length).trimStart();
        prefixRemoved = true;
        break;
      }
    }
  }
  normalized = normalized.replace(/\s+/g, ' ').trim();
  if (!normalized) {
    return null;
  }
  normalized = STREET_ALIASES[normalized] ?? normalized;
  return normalized || null;
}

const NORMALIZED_SPLIT_CONFIG: Record<string, SplitRule[]> = Object.fromEntries(
  Object.entries(SPLIT_STREETS_CONFIG).map(([key, rules]) => [
    normalizeStreetKey(key) ?? key,
    rules,
  ])
);

const NORMALIZED_STREET_MAP: Record<string, string> = Object.fromEntries(
  Object.entries(STREET_TO_DISTRICT_MAP).map(([key, district]) => [
    normalizeStreetKey(key) ?? key,
    district,
  ])
);

const NORMALIZED_STREET_ENTRIES = Object.entries(NORMALIZED_STREET_MAP);

function findStreetBySuffixMatch(normalizedKey: string): string | null {
  const tokens = normalizedKey.split(' ').filter(Boolean);
  if (!tokens.length) {
    return null;
  }
  for (let suffixLength = tokens.length; suffixLength >= 1; suffixLength--) {
    const suffix = tokens.slice(-suffixLength).join(' ');
    let match: string | null = null;
    let matchesCount = 0;
    for (const [key, district] of NORMALIZED_STREET_ENTRIES) {
      if (key === suffix || key.endsWith(` ${suffix}`)) {
        matchesCount += 1;
        match = district;
        if (matchesCount > 1) {
          break;
        }
      }
    }
    if (matchesCount === 1 && match) {
      return match;
    }
  }
  return null;
}

function parseHouseNumber(numStr: string | null | undefined): number | null {
  if (!numStr) return null;
  const match = numStr.match(/\d+/);
  return match ? parseInt(match[0], 10) : null;
}

function resolveSplitStreet(
  street: string | null | undefined,
  numberStr: string | null | undefined
): string | null {
  if (!street) {
    return null;
  }
  const normalizedKey = normalizeStreetKey(street);
  if (!normalizedKey) {
    return null;
  }
  const rules = NORMALIZED_SPLIT_CONFIG[normalizedKey];
  if (!rules?.length) {
    return null;
  }
  const houseNumber = parseHouseNumber(numberStr);
  if (houseNumber === null) {
    return null;
  }
  const parity = houseNumber % 2 === 0 ? 'EVEN' : 'ODD';
  for (const rule of rules) {
    if (rule.parity !== 'BOTH' && rule.parity !== parity) {
      continue;
    }
    if (houseNumber >= rule.min && houseNumber <= rule.max) {
      return rule.district;
    }
  }
  return null;
}

export function normalizeLocation(
  city: string | null | undefined,
  rawDistrict: string | null | undefined,
  rawStreet: string | null | undefined,
  rawStreetNumber: string | null | undefined
): string | null {
  const normalizedCity = city
    ? stripDiacritics(city).trim().toLowerCase()
    : null;
  const isCzestochowa = normalizedCity === 'czestochowa';

  if (!isCzestochowa) {
    return rawDistrict ? formatDistrictName(rawDistrict) : null;
  }

  if (rawStreet) {
    const splitDistrict = resolveSplitStreet(rawStreet, rawStreetNumber);
    if (splitDistrict) {
      return formatDistrictName(splitDistrict);
    }
    const normalizedStreetKey = normalizeStreetKey(rawStreet);
    if (normalizedStreetKey) {
      const mappedDistrict = NORMALIZED_STREET_MAP[normalizedStreetKey];
      if (mappedDistrict) {
        return formatDistrictName(mappedDistrict);
      }
      const suffixMatch = findStreetBySuffixMatch(normalizedStreetKey);
      if (suffixMatch) {
        return formatDistrictName(suffixMatch);
      }
    }
  }

  if (rawDistrict) {
    if (
      OFFICIAL_DISTRICTS.includes(
        rawDistrict.toUpperCase() as (typeof OFFICIAL_DISTRICTS)[number]
      )
    ) {
      return formatDistrictName(rawDistrict);
    }
    const districtLower = rawDistrict.toLowerCase();
    const matchedOfficial = OFFICIAL_DISTRICTS.find(
      official =>
        official.toLowerCase().includes(districtLower) ||
        districtLower.includes(official.toLowerCase())
    );
    if (matchedOfficial) {
      return formatDistrictName(matchedOfficial);
    }
  }

  return rawDistrict ? formatDistrictName(rawDistrict) : null;
}
